### ISSUE TITLE
Migrate to Gradle

### ISSUE THREAD

**Issue by NyCodeGHG** [DerBanko/BoardGames#1]
I think you should migrate to gradle because it's just better and xml in 2021 is really bad. :^)

[Gradle Configuration](https://gist.github.com/NyCodeGHG/84d67bfa37f665ed2efab604c3a690b2)

**Comment by DRSchlaubi** [comment]
Yeah what the other dude said

**Comment by DRSchlaubi** [comment]
![](https://rice.by.devs-from.asia/chrome_YoBIy2dCUt.png)

🤔

**Comment by DRSchlaubi** [comment]
I want to point out that #2 would fix this
